version: '3'

services:
  vaultserver:
    image: vault:latest
    container_name: vaultserver
    hostname: vaultserver
    restart: unless-stopped
    stdin_open: true
    tty: true
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "roottoken"
    ports:
      - "8200:8200"
